version: "3.2"

services:
  sun-panel:
    image: 'ghcr.io/75412701/sun-panel-v2:latest'
    container_name: sun-panel-v2
    volumes:
    - ./conf:/app/conf
    - ./uploads:/app/uploads
    - ./database:/app/database
    # - ./runtime:/app/runtime
    ports:
    - 3002:3002
    restart: always
